services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - /home/abaddon/Projects/SecureEnvironments/Python/dashboard-of-conan/.env
    environment:
      - FLASK_APP=app/main.py
    command: flask run --host=0.0.0.0 --port=5000 --debug